version : '3.8'

services:
    postgres:
        image: postgres:15.13
        container_name: itemmanagement-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: user111
            POSTGRES_DB: itemmanagement
        networks:
            - itemmanagement-network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: itemmanagement-springboot-app
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/itemmanagement
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: user111
        depends_on:
            - postgres
        networks:
            - itemmanagement-network
networks:
    itemmanagement-network:
        name: itemmanagement-network


    
            
            
        